### ISSUE TITLE
Mixed up registers

### ISSUE THREAD

**Issue by metapsychologe** [PacktPublishing/Embedded-Systems-Architecture-Second-Edition#1]
https://github.com/PacktPublishing/Embedded-Systems-Architecture-Second-Edition/blob/87637ca90df0cd76956ef6172d2e33f4046915d0/Chapter10/os-safe/locks.S#L53
Shouldn't this be
```
CMP R1, #1
```
R0 contains the input argument while R1 contains the incremented counter value.

**Comment by danielinux** [comment]
You are right, this looks like a typo.

**Comment by danielinux** [comment]
Fixed, thank you!
